
CREATE TABLE extras (id INTEGER PRIMARY KEY AUTO_INCREMENT,name TEXT,value1 TEXT,value2 text,value3 text);
INSERT INTO extras VALUES(1,'teamNow','India','Pak','');
INSERT INTO extras VALUES(2,'bb','','','');
INSERT INTO extras VALUES(3,'batPlayer','7','8','');
INSERT INTO extras VALUES(4,'ballPlayer','2','','');
INSERT INTO extras VALUES(5,'matchNow','1','','');
DROP TABLE IF EXISTS "android_metadata";
CREATE TABLE balls (id INTEGER PRIMARY KEY AUTO_INCREMENT,matchId int,ballNo int,score int,playerBat int,PlayerBall int,teamName text,noballrun int,noball int,wiedball int);
CREATE TABLE metch (id INTEGER PRIMARY KEY AUTO_INCREMENT,team1 text,team2 text,overs int,firstBat text);
INSERT INTO metch VALUES(1,'India','Pak',1,NULL);
CREATE TABLE overs (id INTEGER PRIMARY KEY AUTO_INCREMENT,matchId int,playerId int,ballStart int,ballEnd int,other text);
DROP TABLE IF EXISTS players;
CREATE TABLE players (id INTEGER PRIMARY KEY AUTO_INCREMENT,name TEXT,type TEXT,teamId int,other text);
INSERT INTO players VALUES(1,'p1','bat','Pak',NULL);
INSERT INTO players VALUES(2,'p2','bat','Pak',NULL);
INSERT INTO players VALUES(3,'p3','bat','Pak',NULL);
INSERT INTO players VALUES(4,'p4','bat','Pak',NULL);
INSERT INTO players VALUES(5,'p5','bat','Pak',NULL);
INSERT INTO players VALUES(6,'p6','bat','Pak',NULL);
INSERT INTO players VALUES(7,'I1','bat','India',NULL);
INSERT INTO players VALUES(8,'I2','bat','India',NULL);
INSERT INTO players VALUES(9,'I3','bat','India',NULL);
INSERT INTO players VALUES(10,'I4','bat','India',NULL);
INSERT INTO players VALUES(11,'I5','bat','India',NULL);
INSERT INTO players VALUES(12,'I6','bat','India',NULL);
CREATE TABLE teams (id INTEGER PRIMARY KEY AUTO_INCREMENT,name TEXT,other text);
INSERT INTO teams VALUES(1,'India',NULL);
INSERT INTO teams VALUES(2,'Pak',NULL);
CREATE TABLE wickets (id INTEGER PRIMARY KEY AUTO_INCREMENT,matchId int,playerId int,other text,teamName text,ballNo text,playerball text);
